### ISSUE TITLE
Regarding usage of repo

### ISSUE THREAD

**Issue by Bioinf-usr** [ifct2017/ifct2017.github.io#1]

**Comment by wolfram77** [comment]
Startup?

**Comment by Bioinf-usr** [comment]
Hi,

Yes, it is regarding the startup. Would you be available for a call to discuss about the resources that you used?

Thanks,

Regards,
Dheeraj

**Comment by wolfram77** [comment]
Ok you can create a google meet at 6 or later and send me a link.

**Comment by Bioinf-usr** [comment]
Could you please provide me your email id?

Regards,
Dheeraj

**Comment by wolfram77** [comment]
wolfram77@gmail.com
